// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fa42626f-0b4b-4c6a-98ff-06128cf29767",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5LmmITn4Y",
    "aws_user_pools_web_client_id": "5584ne79urffm44nj5bmugk84",
    "oauth": {
        "domain": "auth-appenv.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "https://userarx.com/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://cqz6akzsyfcwtdnnwhnkad3zoi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jwmjhjtjpfhglgy7fw33c4ux6y"
};


export default awsmobile;
