// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0d4f046f-9494-4566-a14e-78fbbd857f06",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PgB8yV5aa",
    "aws_user_pools_web_client_id": "72k99fbb6v23r78rj8t6lgtqgk",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ccqgqrlvb5ddzjvehg3lc7kz3y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-jwmjhjtjpfhglgy7fw33c4ux6y"
};


export default awsmobile;
