// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://cqz6akzsyfcwtdnnwhnkad3zoi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jwmjhjtjpfhglgy7fw33c4ux6y",
    "aws_cognito_identity_pool_id": "us-east-1:086ba42c-76d0-402a-90fb-973649de3202",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2EtGqqKEK",
    "aws_user_pools_web_client_id": "72ak6rudo4vh8ecs4qvp8m0c1r",
    "oauth": {}
};


export default awsmobile;
